### ISSUE TITLE
New font

### ISSUE THREAD

**Issue by leonardoobaptistaa** [Ruppy/laser-game#16]

**Comment by leonardoobaptistaa** [comment]
@gvanilla please send the new font.

**Comment by leonardoobaptistaa** [comment]
@gvanilla PLEASE!

**Comment by leonardoobaptistaa** [comment]
@gvanilla WHERE IS THE NEW FONT??????

**Comment by gvanilla** [comment]
here it is :)
[Finalmente a Fonte do jogo](https://github.com/Ruppy/laser-game/files/5619069/Fonte.zip)

**Comment by leonardoobaptistaa** [comment]
@vitallan ⬆️
