### ISSUE TITLE
Font is too big on Glaucia's browser

### ISSUE THREAD

**Issue by leonardoobaptistaa** [Ruppy/laser-game#42]

**Comment by gvanilla** [comment]
![Screen Shot 2020-12-11 at 18 52 19](https://user-images.githubusercontent.com/4043709/101958591-65b5e800-3be2-11eb-9ae3-8f65c91d7bd4.png)

**Comment by leonardoobaptistaa** [comment]
Checking for updates
Version 87.0.4280.67 (Official Build) (x86_64)
